export default {
  INJECT_WEB3: "INJECT_WEB3",
  INJECT_WEB3_SUCCESS: "INJECT_WEB3_SUCCESS",
  INJECT_WEB3_FAIL: "INJECT_WEB3_FAIL",

  LOAD_CONTRACT: "LOAD_CONTRACT",
  LOAD_CONTRACT_SUCCESS: "LOAD_CONTRACT_SUCCESS",

  LOAD_TOTAL_LISTS: "LOAD_TOTAL_LISTS",
  LOAD_TOTAL_LISTS_SUCCESS: "LOAD_TOTAL_LISTS_SUCCESS",

  LOAD_LIST_IDS: "LOAD_LIST_IDS",
  LOAD_LIST_IDS_SUCCESS: "LOAD_LIST_IDS_SUCCESS",

  LOAD_LIST: "LOAD_LIST",
  LOAD_LIST_SUCCESS: "LOAD_LIST_SUCCESS"
}

