
// SET is setting loader, flash massages or other ui related things
// LOAD is loading libs and contract information from the local browser environment. no blockchain involved
// CALL is reading data from the blockchain. data is synchronously available(50ms). no eth needed
// SEND is changing data on the blockchain. data is asynchronously available(~14-17 seconds). block needs to be mined before transaction is performed. eth needed


export default {
  SET_HISTORY: "SET_HISTORY",
  SET_LOADING: "SET_LOADING",
  SET_FLASH: "SET_FLASH",

  SET_LIST_TAMPLATE: "SET_LIST_TAMPLATE",



  LOAD_WEB3: "LOAD_WEB3",
  LOAD_WEB3_SUCCESS: "LOAD_WEB3_SUCCESS",
  LOAD_WEB3_FAIL: "LOAD_WEB3_FAIL",

  LOAD_CONTRACT: "LOAD_CONTRACT",
  LOAD_CONTRACT_SUCCESS: "LOAD_CONTRACT_SUCCESS",

  CALL_TOTAL_LISTS: "CALL_TOTAL_LISTS",
  CALL_TOTAL_LISTS_SUCCESS: "CALL_TOTAL_LISTS_SUCCESS",

  CALL_LIST_IDS: "CALL_LIST_IDS",
  CALL_LIST_IDS_SUCCESS: "CALL_LIST_IDS_SUCCESS",

  CALL_LIST: "CALL_LIST",
  CALL_LIST_SUCCESS: "CALL_LIST_SUCCESS",



  SEND_CREATE_LIST: "SEND_CREATE_LIST",
  SEND_CREATE_LIST_STARTED: "SEND_CREATE_LIST_STARTED",
  SEND_CREATE_LIST_SUCCESS: "SEND_CREATE_LIST_SUCCESS",

  SEND_UPDATE_LIST: "SEND_UPDATE_LIST",
  SEND_UPDATE_LIST_STARTED: "SEND_UPDATE_LIST_STARTED",
  SEND_UPDATE_LIST_SUCCESS: "SEND_UPDATE_LIST_SUCCESS",

  SEND_DELETE_LIST: "SEND_DELETE_LIST",
  SEND_DELETE_LIST_STARTED: "SEND_DELETE_LIST_STARTED",
  SEND_DELETE_LIST_SUCCESS: "SEND_DELETE_LIST_SUCCESS",
}

